# Site settings
title: "Vitiral: vital literal trivial content, probably not viral."
email: vitiral@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Blog about life and linux
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vitiral.github.com" # the base hostname & protocol for your site
twitter_username: vitiral
github_username:  vitiral

# Build settings
markdown: kramdown
kramdown:
    input: GFM
